# TRAINING PARAMETERS
seed: 123
val_test_ratio: [0.06, 0.06]
n_epochs: 5
batch_size: 32
val_batch_size: 128
shuffle: True


# MODEL HYPERPARAMETERS
model_name: 'model_00'
gan: False

len_input: 250
encoder_lstm_units: 250

conv_filters: [8, 16]
conv_activation: 'elu'
conv_initializer: 'he_normal'
use_batchnorm: True

decoder_lstm_units: 250
decoder_dense_units: 200
decoder_dense_activation: 'elu'
decoder_output_activation: 'relu'


# GAN HYPERPARAMETERS
noise_dims: 50
discriminator_lstm_units: 250

discriminator_dense_units: 200
discriminator_activation: 'elu'


# DETERIORATION PARAMETERS
prob_noise: 0.75     # probability of noise
exp_scale: 165.496   # variance of exponential distribution
interval_ratio: [0.01, 0.4]
prob_interval: 0.5
placeholder_value: -0.1  # what value to be fed instead of NaN
