# MAIN
model_name: 'vanilla_seq2seq_00'
gan: False
check_test_performance: True  # After training, load Test data and check test loss


# MODEL HYPERPARAMETERS
use_gpu: True
seed: 123
val_test_ratio: [0.06, 0.06]
n_epochs: 3
batch_size: 64
learning_rate: 0.0001
shuffle: True

len_input: 150

kernel_size: 3
conv_filters: [8, 16]
conv_activation: 'elu'
conv_initializer: 'he_normal'
use_batchnorm: True
conv_dropout: 0.1

decoder_dense_units: 50
decoder_dense_activation: 'elu'
decoder_output_activation: 'relu'
decoder_dense_initializer: 'he_normal'
decoder_dense_dropout: 0.1


# GAN HYPERPARAMETERS
noise_dims: 50
discriminator_lstm_units: 250

discriminator_dense_units: 200
discriminator_activation: 'elu'


# DETERIORATION PARAMETERS
prob_noise: 0.75     # probability of noise
exp_scale: 165.496   # variance of exponential distribution
interval_ratio: [0.01, 0.4]
prob_interval: 0.5
placeholder_value: -0.1  # what value to be fed instead of NaN
