# MAIN
model_name: 'prova' #'vanilla_seq2seq_02'
# Model types:
    # 1: Vanilla seq2seq
    # 2: GAN
    # 3: Seq2seq with partially adversarial training
model_type: 1
use_gpu: True
# After training, load Test data and check test loss
check_test_performance: True


# MODEL HYPERPARAMETERS
seed: 123
val_test_ratio: [0.06, 0.06]
train_size_per_epoch: 50000
n_epochs: 1
batch_size: 64
learning_rate: 0.0001
# shuffle: True

len_input: 128

kernel_size: 3
conv_filters: [8, 16]
conv_activation: 'elu'
conv_initializer: 'he_normal'
use_batchnorm: True
conv_dropout: 0.1

decoder_dense_units: 50
decoder_dense_activation: 'elu'
decoder_output_activation: 'relu'
decoder_dense_initializer: 'he_normal'
decoder_dense_dropout: 0.1


# GAN HYPERPARAMETERS
noise_dims: 50
discriminator_lstm_units: 250

discriminator_dense_units: 100
discriminator_activation: 'elu'


# DETERIORATION PARAMETERS
# ratio of total NaN's at each deterioration
total_nan_range: [0.12, 0.25]
# probability of random noise vs interval noise
prob_noise: 0.5
# what value to be fed instead of NaN
placeholder_value: -0.1
